name: cnc_app
description: Carrer & Counselling Flutter application

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  fluttertoast: ^8.0.6
  cloud_firestore: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

